### ISSUE TITLE
ToDo(개발)

### ISSUE THREAD

**Issue by siraegi** [OHuIShI/LinkSafariAndChromeTabs#1]
- [ ] AWS DB 종류 선택 - RDB? NoSQL?
- [ ] DB 스키마
- [ ] 애플 development 계정 생성 결제
- [ ] 크롬 확장 프로그램 만드는 법 알아보기
